import type { Metadata } from 'next'
import '../../../../globals.css'
import 'react-toastify/dist/ReactToastify.css'
import FooterNavigationBar from '@/app/globalcomponents/FooterNav'
import FreemiumAccount from './components/Freemium'
import SearchBox from '@/app/globalcomponents/SearchBox'
import Image from 'next/image'
import ContentCard from '../components/ContentCard'

export const metadata: Metadata = {
  title: 'Learning Modules | Get to work',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <div className='md:hidden relative flex flex-col bg-white px-[1.25rem] py-[3rem] w-full h-auto min-h-screen'>
        <div className='mb-[1rem] search'>
          <SearchBox placeholder='for lessons' />
        </div>
        <div className='freemium'>
          <FreemiumAccount />
        </div>
        <div className='recommended'>
          <div className='flex justify-between items-center'>
            <h2 className='mt-4 mb-4 font-bold text-[16px]'>Recommended For You</h2>
            <Image src='/lock.png' alt='lock' width={30} height={30} />
          </div>
          <ContentCard
            alt='collaborate'
            imageUrl='/image 45.png'
            textHead='Collaborate with your peers'
            routeTo='/'
          />
        </div>
        {children}
      </div>

      <div className='md:hidden bottom-0 left-0 z-50 fixed flex w-full footer_nav_bar'>
        <FooterNavigationBar
          dashboardRouteTo='/learningapp/dashboard'
          homeRouteTo='/learningapp/home'
          inboxRouteTo='/learningapp/inbox'
          profileRouteTo='/learningapp/profile'
        />
      </div>
    </>
  )
}
