import type { Metadata } from 'next'
import '../globals.css'
import 'react-toastify/dist/ReactToastify.css'
import ParentHeader from '../components/ParentHeader'
import PSideNav from '../components/ParentSideNav'

export const metadata: Metadata = {
  title: 'Welcome | Learnsphere',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <div className='bg-white w-full h-auto min-h-screen'>
        {/* Parent header */}
        <ParentHeader />

        {/* Page-specific content */}
        <div className='flex'>
          {/* side nav */}
          <div className='bg-white w-[23%]'>
            <PSideNav />
          </div>
          {/* content */}
          <div className='mx-[20px] w-[77%]'>{children}</div>
        </div>
      </div>
    </>
  )
}
