import type { Metadata } from 'next'
import '../globals.css'
import 'react-toastify/dist/ReactToastify.css'
import FooterNavigationBar from '../globalcomponents/FooterNav'

export const metadata: Metadata = {
  title: 'LearningApp | Learnsphere',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <div className='relative flex flex-col bg-white w-full h-auto min-h-screen'>
        {children}
      </div>

      <div className='md:hidden bottom-0 left-0 z-50 fixed flex w-full footer_nav_bar'>
        <FooterNavigationBar
          dashboardRouteTo='/learningapp/dashboard'
          homeRouteTo={'/learningapp/home' }
          inboxRouteTo='/learningapp/inbox'
          profileRouteTo='/learningapp/profile'
        />
      </div>
    </>
  )
}
